name: Test & Ship

on:
- push
- pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      COMPOSER_PROCESS_TIMEOUT: 0
    
    strategy:
      matrix:
        php_version:
          - 7.3

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php_version }}
        tools: composer:1.10.19
        
    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
        
    - name: Setup environment
      run: |
        set -e;
        composer install --no-interaction ;
        
    - name: Run tests
      run: |
        set -e;

        # TBD
        true;

  
  ship:
    needs: [ test ]
    if: github.event_name == 'push'   # not on PRs
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Get ECR password
      id: get-ecr-password
      run: echo "::set-output name=password::$(aws ecr get-login-password)"

    - name: Build and push to Amazon ECR
      uses: docker/build-push-action@v1
      with:
        registry: 513259414768.dkr.ecr.eu-west-1.amazonaws.com
        repository: ussd-engine
        username: AWS
        password: ${{ steps.get-ecr-password.outputs.password }}
        always_pull: true
        tag_with_sha: true
        tag_with_ref: true

    - name: Logout from Amazon ECR
      if: always()
      run: docker logout ${{ steps.login-ecr.outputs.registry }}
